### ISSUE TITLE
Consider relicensing under a different license

### ISSUE THREAD

**Issue by jaredsmith** [dcodeIO/opt.js#1]
Would you please consider relicensing this code under a different license?  The Free Software Foundation (and several Linux distributions, such as Fedora) find that the NASA license includes restrictions that make this license incompatible with free software.

**Comment by tysenmoore-xse** [comment]
I second this request.  I use your protobufjs, and do not use the command line execution of the module.  However, optjs is still listed as a dependency (from ascli).  I'd prefer to not fork protobufjs to remove this dependency. Is there any way you would consider using a different license (MIT, Apache, BSD)?  Is there a specific reason for your choice of using the NASA license?

**Comment by jaredsmith** [comment]
Can you also provide a LICENSE file?  I hate to be a stickler, but the MIT license requires that the text of the license accompany the source code.  (The same would be true for the BSD license, etc.)
